# Usa la imagen oficial de Nginx como base
FROM nginx:latest

# Copia el archivo index.html modificado a la carpeta correspondiente en el contenedor
COPY index.html /usr/share/nginx/html/index.html

# deja expuest el puerto 80 del contenedor
EXPOSE 80
